language: python
python:
    - "2.7"
    - "3.8"
services:
    - docker
env:
    - OC_VERSION=10.0

before_install:
    - travis-build/setup_oc_docker.sh $OC_VERSION

install:
    - pip install flake8 requests unittest-data-provider six

script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - cp owncloud/test/config.py.sample owncloud/test/config.py
    # execute unit tests
    - ./runtests.sh

